# Generated by Django 5.1.1 on 2024-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0002_alter_sarpras_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='sarpras',
            table='sarpras',
        ),
    ]
