# Generated by Django 5.1.1 on 2024-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sarpras', '0003_alter_sarpras_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sarpras',
            name='KondisiBarang',
            field=models.CharField(choices=[('baik', 'baik'), ('sedang', 'sedang'), ('buruk', 'buruk')], max_length=6),
        ),
    ]
