# Generated by Django 5.1.1 on 2024-10-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_ibuhamil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ibuhamil',
            name='UmurKehamilan',
            field=models.CharField(default=0, max_length=64),
        ),
    ]
