# Generated by Django 5.1.1 on 2024-10-02 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kotaksaran', '0003_alter_kotaksaran_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kotaksaran',
            old_name='IsiKegiatan',
            new_name='IsiSaran',
        ),
    ]
