# Generated by Django 5.1.1 on 2024-09-26 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anggota', '0002_alter_anggotaposyandu_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anggotaposyandu',
            table=None,
        ),
    ]
