# Generated by Django 5.1.1 on 2024-09-25 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rumahJentik',
            fields=[
                ('IdRumah', models.AutoField(primary_key=True, serialize=False)),
                ('NomorRumah', models.CharField(max_length=64)),
                ('KepalaRumah', models.CharField(max_length=64)),
                ('AlamatRumah', models.CharField(max_length=255)),
                ('JumlahKontainer', models.CharField()),
                ('KontainerJentik', models.CharField()),
            ],
            options={
                'db_table': 'rumahJentik',
            },
        ),
    ]
