# Generated by Django 5.1.1 on 2024-09-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_jentik', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rumahjentik',
            table=None,
        ),
    ]
