# Generated by Django 5.1.1 on 2024-09-26 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_jentik', '0002_alter_rumahjentik_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rumahjentik',
            table='rumahJentik',
        ),
    ]
