# Generated by Django 5.1.1 on 2024-09-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jadwalKunjungan',
            fields=[
                ('IdKunjungan', models.AutoField(primary_key=True, serialize=False)),
                ('TanggalKunjungan', models.DateField()),
                ('NamaKunjungan', models.CharField()),
                ('DeskripsiKunjungan', models.CharField()),
            ],
            options={
                'db_table': 'jadwalKunjungan',
            },
        ),
    ]
