# Generated by Django 5.1.1 on 2024-09-26 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_kunjungan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jadwalkunjungan',
            table=None,
        ),
    ]
