# Generated by Django 5.1.1 on 2024-09-26 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_kunjungan', '0002_alter_jadwalkunjungan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jadwalkunjungan',
            table='jadwalKunjungan',
        ),
    ]
