# Generated by Django 5.1.1 on 2024-10-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posbindu',
            fields=[
                ('IdBindu', models.AutoField(primary_key=True, serialize=False)),
                ('NamaBindu', models.CharField(max_length=64)),
                ('AlamatBindu', models.CharField()),
                ('BeratBindu', models.CharField()),
                ('TekananDarahBindu', models.CharField()),
                ('KeluhanBindu', models.CharField()),
            ],
            options={
                'db_table': 'posbindu',
            },
        ),
    ]
