# Generated by Django 5.1.1 on 2024-09-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jadwalkegiatan',
            table=None,
        ),
    ]
