# Generated by Django 5.1.1 on 2024-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jadwal_kegiatan', '0002_alter_jadwalkegiatan_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jadwalkegiatan',
            table='jadwalKegiatan',
        ),
    ]
