# Generated by Django 5.1.1 on 2024-09-25 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bayi',
            fields=[
                ('IdBayi', models.AutoField(primary_key=True, serialize=False)),
                ('NamaBayi', models.CharField(max_length=64)),
            ],
        ),
    ]
