# Generated by Django 5.1.1 on 2024-09-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_bayi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bayi',
            table='bayi',
        ),
    ]
