# Generated by Django 5.1.1 on 2024-09-26 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_bayi', '0003_alter_bayi_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='bayi',
            table='bayi',
        ),
    ]
