# Generated by Django 5.1.1 on 2024-10-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_bayi', '0004_alter_bayi_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bayi',
            name='TanggalLahir',
            field=models.DateField(null=True),
        ),
    ]
